name: Build GitHub Pages

on:
 push:
  branches: [main]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3

   - name: Set up Node.js
     uses: actions/setup-node@v3
     with:
      node-version: 18

    - name: Start local server in background
     run: |
      node index.js &
      echo $! > server.pid
      sleep 5  # give server time to start

   - name: Run static build
     run: node build.js

   - name: Kill server
     run: |
      kill $(cat server.pid) || echo "Server already stopped"
      rm server.pid

  #  - name: Commit docs to main
  #    run: |
  #     git config user.name github-actions
  #     git config user.email github-actions@github.com
  #     git add docs
  #     git commit -m 'Update docs [ci skip]' || echo 'No changes'
  #     git push